{{- if .Values.thanos.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-s3-credentials
  namespace: monitoring
type: Opaque
stringData:
  thanos-s3-credentials.yaml: |-
    type: S3
    config:
      bucket: "thanos-ruler00"
      endpoint: "s3.afranet.net"
      region: "us-east-1"
      access_key: ""
      secret_key: ""
      insecure: true
{{- end }}


