---
# tasks file for set-shecan-dns
- name: DNS | Set shecan dns before download
  shell: sudo resolvectl dns eth0 185.51.200.2 178.22.122.100 && sudo netplan apply
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: DNS | Set shecan dns before download
  shell: echo "nameserver 185.51.200.2">/etc/resolv.conf && echo "nameserver 178.22.122.100">>/etc/resolv.conf
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

