---
# tasks file for rook_ceph
- name: DNS1 | Set shecan dns before download
  shell: resolvectl dns eth0 185.51.200.2 178.22.122.100 && netplan apply
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  args:
    executable: /bin/bash


- name: DNS1 | Set shecan dns before download
  shell: echo "nameserver 185.51.200.2">/etc/resolv.conf && echo "nameserver 178.22.122.100">>/etc/resolv.conf
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  args:
    executable: /bin/bash

- name: Edit mariadb name space
  shell: kubectl create ns mariadb-ns
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: apply galera cluster manifests
  shell: kubectl create -f /vagrant/galera-cluster/etcd-cluster.yaml -f /vagrant/galera-cluster/mariadb-cluster.yaml
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Edit mariadb name space
  shell: /usr/local/bin/kubectl create ns mariadb-ns
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: apply galera cluster manifests
  shell: /usr/local/bin/kubectl create -f /vagrant/galera-cluster/etcd-cluster.yaml -f /vagrant/galera-cluster/mariadb-cluster.yaml
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


