---
# If all masters have node role, there are no tainted master and toleration should not be specified.
- name: Check all masters are node or not
  set_fact:
    masters_are_not_tainted: "{{ groups['kube_node'] | intersect(groups['kube_control_plane']) == groups['kube_control_plane'] }}"

- name: Galera cluster Server | Delete addon dir
  file:
    path: "{{ kube_config_dir }}/addons/galera_cluster"
    state: absent
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
  tags:
    - upgrade

- name: Galera cluster Server | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/galera_cluster"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Galera Server | Templates list
  set_fact:
    Galera_server_templates:
      - { name: etcd-cluster, file: etcd-cluster.yaml }
      - { name: mariadb-cluster, file: mariadb-cluster.yaml }

- name: Galera cluster Server | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ kube_config_dir }}/addons/galera_cluster/{{ item.file }}"
    mode: 0644
  with_items: "{{ Galera_server_templates }}"
  register: Galera_server_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Galera Server | Apply manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/galera_cluster/{{ item.item.file }}"
    state: "present"
  with_items: "{{ Galera_server_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]