---
# If all masters have node role, there are no tainted master and toleration should not be specified.
- name: Check all masters are node or not
  set_fact:
    masters_are_not_tainted: "{{ groups['kube_node'] | intersect(groups['kube_control_plane']) == groups['kube_control_plane'] }}"

- name: ceph rook Server | Delete addon dir
  file:
    path: "{{ kube_config_dir }}/addons/rook_ceph"
    state: absent
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
  tags:
    - upgrade

- name: ceph rook Server | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/rook_ceph"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Ceph Rook Server | Templates list
  set_fact:
    Ceph_rook_server_templates:
      - { name: crds, file: crds.yaml }
      - { name: common, file: common.yaml }
      - { name: operator, file: operator.yaml }
      - { name: cluster, file: cluster.yaml }
      - { name: storageclass, file: storageclass.yaml }

- name: ceph rook Server | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ kube_config_dir }}/addons/rook_ceph{{ item.file }}"
    mode: 0644
  with_items: "{{ Ceph_rook_server_templates }}"
  register: ceph_rook_server_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Ceph Rook Server | Apply manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/rook_ceph/{{ item.item.file }}"
    state: "present"
  with_items: "{{ ceph_rook_server_manifests.results }}"
  wait: true
  wait_timeout: 1200
    wait_condition:
      type: Complete
      status: True
  when:
    - inventory_hostname == groups['kube_control_plane'][0]