---
# tasks file for rook_ceph
- name: DNS1 | Set shecan dns before download
  shell: resolvectl dns eth0 185.51.200.2 178.22.122.100 && netplan apply
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  args:
    executable: /bin/bash


- name: DNS1 | Set shecan dns before download
  shell: echo "nameserver 185.51.200.2">/etc/resolv.conf && echo "nameserver 178.22.122.100">>/etc/resolv.conf
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  args:
    executable: /bin/bash

- name: Installing Monitoring stack (Prometheus & Grafana) with Helm
  shell: helm install monitoring /vagrant/prometheus-ha/
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

